# Hey, Emacs! This is a -*- Python -*- file!
#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
Import('BUILD_ENV opts_dict')

python_FILES = [
    'kanp.py',
    'kcdpg.py',
    'tcp_client.py',
    'kcgi.py',
    'kfs_lib.py',
    'kcd_lib.py',
    'kcd_client.py',
    'ksamba.py']

python_PROGS = [
    'kasmond',
    'kcdhelper',
    'kcdshell']

installs = []

BUILD_ENV.Dir(opts_dict['PYTHONDIR'])

for pf in python_FILES:
    installs.append(BUILD_ENV.Install(dir = opts_dict['PYTHONDIR'], target = pf))

for pp in python_PROGS:
    shName = os.path.splitext(os.path.basename(pp))[0]
    # Predefine LINESEPARATOR or Textfile will choke.
    BUILD_ENV['LINESEPARATOR'] = os.linesep
    psh = BUILD_ENV.Textfile(shName, ["#!/bin/sh",
                                      "export PYTHONPATH=$PYTHONDIR",
                                      "$PYTHONDIR/" + str(pp) + ' $@'])
    installs.append(BUILD_ENV.Install(dir = opts_dict['PYTHONDIR'], target = pp))
    shInst = BUILD_ENV.Install(dir = opts_dict['BINDIR'], target = psh)
    BUILD_ENV.AddPostAction(shInst, Chmod("$TARGET", 0755))
    installs.append(shInst)

Return('installs')
